apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "street-squirrel.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 80%
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "street-squirrel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "street-squirrel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "street-squirrel.shortName" . }}-config
                  key: version
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "street-squirrel.shortName" . }}-config
                  key: postgresHost
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "street-squirrel.shortName" . }}-config
                  key: postgresDatabase
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "street-squirrel.shortName" . }}-config
                  key: postgresUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "street-squirrel.shortName" . }}-secret
                  key: postgresPassword
