apiVersion: v1
kind: Service
metadata:
  name: {{ include "street-squirrel.fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    {{- include "street-squirrel.selectorLabels" . | nindent 4 }}
