# Default values for homepage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: "registry-jnhssg-net-registrycreds"
  - name: "ecr-registrycreds"

image:
  repository: 150156989042.dkr.ecr.eu-central-1.amazonaws.com/street-squirrel
  pullPolicy: IfNotPresent
  tag: ""

service:
  name: http
  port: 8080

ingress:
  enabled: true

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

env:
  LOG_LEVEL: "WARN"

configs:
  version: "v0.0.0"
  postgresHost: "glacier.jnhssg.de"
  postgresDatabase: "streetwise"
  postgresUser: "postgres"
  valhallaUrl: "https://routing.jnhssg.de"

secrets:
  postgresPassword: "ASK_A_DEV"
